// Auto-generated by eacp_add_webview_app — do not edit.
import { defineConfig } from '@playwright/test';
export default defineConfig({
    testDir: '.',
    timeout: 30_000,
    fullyParallel: true,
    forbidOnly: !!process.env['CI'],
    retries: process.env['CI'] ? 1 : 0,
    reporter: process.env['CI'] ? 'github' : 'list',
});
