export { createRpcClient, RpcError, type RpcClient } from './client.ts';
export { AppDriver, type AppDriverOptions, type CallOptions } from './AppDriver.ts';
export { launchApp, type LaunchOptions, type LaunchedApp } from './launch.ts';

// Note: the Playwright runner surface (`test`, `expect`,
// `defineConfig`) is NOT re-exported here. Doing so would force the
// framework's real path to resolve `@playwright/test`, which fails
// when this package is imported from outside its own dir (e.g. via
// the per-app shim generated by eacp_add_webview_app). The CMake
// helper generates a `tests-node/eacp-test-node.ts` shim that
// re-exports both this module *and* `@playwright/test` from the
// consumer-side node_modules, so specs still import everything from
// a single local path.
