include(CPM)

# The three pieces the Vulkan backend needs that are not on the machine: the
# headers, the loader stub and the allocator. Fetched the way glslang is
# (FindGlslang.cmake), pinned and shallow, and included only from the Linux
# branch of Lib/eacp/GPU/CMakeLists.txt - a macOS or Windows configure fetches
# none of it.
#
# Nothing links libvulkan. volkInitialize() dlopens libvulkan.so.1 at runtime,
# so the build needs no Vulkan package at all and the same binary runs on a
# machine that has no driver - Device::isValid() is false there, which is the
# answer the GPU tests already self-skip on. VK_NO_PROTOTYPES is what holds it
# to that: every entry point is a volk function pointer, and a direct call to a
# loader symbol is a link error rather than a silent dependency.
#
# Vulkan-Headers and volk are pinned to the same SDK tag on purpose: volk's
# generated table is written against one header revision and a mismatch is a
# missing symbol per function added in between.

set(EACP_VULKAN_SDK_TAG vulkan-sdk-1.4.313.0)
set(EACP_VMA_TAG v3.4.0)

# DOWNLOAD_ONLY for all three rather than add_subdirectory. Vulkan-Headers and
# VMA are directories of headers with a CMake project wrapped round them, and
# volk's own CMakeLists decides where to find the headers by probing for a
# find_package(Vulkan) that must not succeed here. Compiling volk.c ourselves
# against the headers we fetched is both shorter and the only version that
# cannot pick up a system SDK by accident.
function(eacp_fetch_vulkan_sources)
    CPMAddPackage(
            NAME VulkanHeaders
            GITHUB_REPOSITORY KhronosGroup/Vulkan-Headers
            GIT_TAG ${EACP_VULKAN_SDK_TAG}
            GIT_SHALLOW YES
            DOWNLOAD_ONLY YES
            SYSTEM YES)

    CPMAddPackage(
            NAME volk
            GITHUB_REPOSITORY zeux/volk
            GIT_TAG ${EACP_VULKAN_SDK_TAG}
            GIT_SHALLOW YES
            DOWNLOAD_ONLY YES
            SYSTEM YES)

    CPMAddPackage(
            NAME VulkanMemoryAllocator
            GITHUB_REPOSITORY GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
            GIT_TAG ${EACP_VMA_TAG}
            GIT_SHALLOW YES
            DOWNLOAD_ONLY YES
            SYSTEM YES)

    set(VulkanHeaders_SOURCE_DIR "${VulkanHeaders_SOURCE_DIR}" PARENT_SCOPE)
    set(volk_SOURCE_DIR "${volk_SOURCE_DIR}" PARENT_SCOPE)
    set(VulkanMemoryAllocator_SOURCE_DIR
            "${VulkanMemoryAllocator_SOURCE_DIR}" PARENT_SCOPE)
endfunction()

# One target for consumers to link, so which of the three a symbol came from
# stays an implementation detail of this module. Static rather than interface
# because two of them ship exactly one translation unit each - volk's dispatch
# table and the allocator's implementation - and a target of their own is what
# keeps those two out of eacp-gpu's unity build, where a 15,000-line header
# would be merged into the same TU as the backend.
if (NOT TARGET eacp-vulkan)
    eacp_fetch_vulkan_sources()

    # file(CONFIGURE) rather than file(WRITE): it leaves the file alone when the
    # content has not changed, so a reconfigure does not rebuild the allocator.
    file(CONFIGURE
            OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/eacp-vma.cpp"
            CONTENT [[
// Generated by CMake/FindVulkanBackend.cmake. The one translation unit that
// compiles VulkanMemoryAllocator. volk.h comes first so the declarations VMA
// finds are the function-pointer ones.
#include <volk.h>

#define VMA_IMPLEMENTATION
#include <vk_mem_alloc.h>
]]
            @ONLY)

    add_library(eacp-vulkan STATIC
            "${volk_SOURCE_DIR}/volk.c"
            "${CMAKE_CURRENT_BINARY_DIR}/eacp-vma.cpp")

    target_include_directories(eacp-vulkan SYSTEM PUBLIC
            "${VulkanHeaders_SOURCE_DIR}/include"
            "${volk_SOURCE_DIR}"
            "${VulkanMemoryAllocator_SOURCE_DIR}/include")

    # VK_NO_PROTOTYPES is PUBLIC because it changes what <vulkan/vulkan.h>
    # declares, and every consumer includes it through volk.h.
    #
    # The two VMA switches are the volk recipe: no link-time Vulkan symbols to
    # find (there are none), and the rest of the table fetched through the
    # vkGetInstanceProcAddr / vkGetDeviceProcAddr pair VulkanShared hands it.
    # VK_USE_PLATFORM_WAYLAND_KHR is PUBLIC for the same reason and one more:
    # volk.c has to see it too, or vkCreateWaylandSurfaceKHR is missing from the
    # dispatch table the backend calls it through. It drags in no dependency -
    # vulkan_wayland.h forward-declares `struct wl_display` and
    # `struct wl_surface` and includes no Wayland header at all - so eacp-gpu
    # creates a surface over the two opaque pointers Graphics/View/View-Linux.h
    # hands it without linking or including libwayland.
    target_compile_definitions(eacp-vulkan PUBLIC
            VK_NO_PROTOTYPES
            VK_USE_PLATFORM_WAYLAND_KHR
            VMA_STATIC_VULKAN_FUNCTIONS=0
            VMA_DYNAMIC_VULKAN_FUNCTIONS=1
            VMA_VULKAN_VERSION=1003000)

    # The loader is opened by name at runtime, so the only library involved is
    # the one that does the opening.
    target_link_libraries(eacp-vulkan PUBLIC ${CMAKE_DL_LIBS})

    # VMA is a third-party header that does not compile clean under eacp's
    # warning set, and it is included by the backend as well as by the
    # generated TU above.
    target_compile_options(eacp-vulkan PRIVATE
            $<$<CXX_COMPILER_ID:GNU,Clang>:-w>)

    set_target_properties(eacp-vulkan PROPERTIES
            POSITION_INDEPENDENT_CODE ON
            FOLDER "${CMAKE_FOLDER}")
endif ()
