#pragma once

// The header set every eacp translation unit parses anyway. Precompiling it
// once is worth a large fraction of a cold Windows build, where <windows.h>
// alone is bigger than the rest of a typical TU put together.
//
// Only headers from outside this repository belong here. eacp's own headers
// would precompile faster still, but any edit to one would invalidate the image
// and turn every incremental build into a full rebuild.
//
// The payload is C++-only on purpose. CMake builds one image per language of
// every consuming target, and the C consumers here are ResEmbed's generated
// byte-array blobs, which include nothing and would only pay to load it.
#ifdef __cplusplus

#ifdef _WIN32
// The configuration eacp/Core/Utils/WinInclude.h applies, spelled out
// rather than included so the image depends on nothing in the repo.
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#ifndef NOMINMAX
#define NOMINMAX
#endif

#include <windows.h>

// No <unknwn.h> here, deliberately. WinInclude.h pairs it with windows.h
// for the WinRT interop TUs, but it drags in rpcndr.h, whose `small`
// macro would then be forced on every file in the project.
#endif

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <deque>
#include <filesystem>
#include <fstream>
#include <functional>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <set>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

#else

// ResEmbed's generated byte arrays are the only C here and include nothing of
// their own, but a translation unit that declares nothing at all is C4206.
#include <stddef.h>

#endif
