#pragma once

// The header set every eacp translation unit parses anyway: the STL, and
// nothing else. Precompiling it is worth about a third of a typical
// translation unit -- 692ms down to 475ms, measured on a Windows build.
//
// <windows.h> is deliberately absent, and adding it back would be a mistake
// worth naming. CMake builds a precompiled header with /FI, so whatever is
// listed here is force-included into every file in the project, and windows.h
// carries a couple of dozen macros with it. `near` and `far` are the dangerous
// ones, being lowercase and so sharing a namespace with every member and
// variable this codebase declares; they cost the Windows lanes a build once, on
// a test whose `near`/`far` members preprocessed down to `.depth = nearDepth;`.
// Undefining them is not a way out -- FAR and NEAR expand to them, and the SDK
// still writes `LPMALLOC FAR *`. Measured, it bought the ~87% of files that
// never include it exactly nothing (475ms with an STL-only image against 478ms
// with windows.h added), while the *-Windows.cpp TUs that do want it pay a flat
// ~68ms each to parse it through WinInclude.h instead. The two defines that
// configure it live in CMake/TargetSetup.cmake, where they apply with EACP_PCH
// off as well.
//
// Only headers from outside this repository belong here. eacp's own headers
// would precompile faster still, but any edit to one would invalidate the image
// and turn every incremental build into a full rebuild.
//
// The payload is C++-only on purpose. CMake builds one image per language of
// every consuming target, and the C consumers here are ResEmbed's generated
// byte-array blobs, which include nothing and would only pay to load it.
#ifdef __cplusplus

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <deque>
#include <filesystem>
#include <fstream>
#include <functional>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <set>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

#else

// ResEmbed's generated byte arrays are the only C here and include nothing of
// their own, but a translation unit that declares nothing at all is C4206.
#include <stddef.h>

#endif
